### ISSUE TITLE
[FEATURE] Name points according to list

### ISSUE THREAD

**Issue by lavender22** [morganjwilliams/autopew#15]
**Is your feature request related to a problem? Please describe.**
Points usually already have names and importing them into the laser software would save some time and lower data handling mistakes.

**Describe the solution you'd like**
import the point label from the X,Y coordinates file

**Comment by morganjwilliams** [comment]
This has been added in 06d10f621772c716c1cc904249529d7153682ec5 by changing the 'spotname_prefix' keword to 'spotnames' which now accepts None (integer based index), a string (as before, used as a prefix) or a list (of the same size as the xy-coordinate list) which contains spot names.
